export { default as Header } from './header';
export { default as Hero } from './hero';
export { default as Navv } from './nav';
export { default as Products } from './products';
export { default as Services } from './services';
export { default as AboutCompany } from './about-company';
export { default as News } from './news';
export { default as Partners } from './partners';
export { default as Footer } from './footer';
